In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import pickle
device = 'mps' if torch.mps.is_available() else 'cpu'
print(device)
block_size = 64
"""batch_size = 128
max_iters = 1000
eval_interval = 500
learning_rate = 3e-4
eval_iters = 100
dropout = 0.2
n_embd = 384
n_layer = 8
n_head = 8"""
block_size = 128
max_iters = 200
learning_rate = 3e-4
eval_iters = 100
n_embd = 384
n_head = 1
n_layer = 1
dropout = 0.2


mps


In [27]:
chars = ""
with open('/Users/padraigobrien/Downloads/API_LLM/.venv/archive/vocab.txt', 'r', encoding = 'utf-8') as f:
    text = f.read()
    chars = sorted(list(set(text)))
vocab_size = len(chars)

In [28]:
import torch
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([16083,     1,  3703,     1, 17125,     1, 18601,     1,  2880,     1,
        28551,     1,  9546,     1, 30469,     1, 31335,     1,  7243,     1,
        10592,     1,  9874,     1, 13706,     1,  9260,     1, 23967,     1,
        30474,     1,  8465,     1,   829,     1, 31576,     1, 13237,     1,
         5125,     1, 17182,     1, 26777,     1, 13667,     1, 20888,     1,
        12148,     1, 12792,     1, 22388,     1, 20837,     1, 25869,     1,
        10365,     1, 28355,     1, 21518,     1,  5111,     1, 18405,     1,
        10252,     1, 21591,     1,  8714,     1,  5301,     1, 18639,     1,
        26468,     1, 24676,     1, 21253,     1, 11664,     1,  1428,     1,
         4572,     1, 13476,     1, 30505,     1,  9893,     1, 26700,     1])


In [29]:
import mmap
import random

def get_random_chunk(split):
    filename = "/Users/padraigobrien/Downloads/API_LLM/.venv/archive/train_split.txt" if split == 'train' else '/Users/padraigobrien/Downloads/API_LLM/.venv/archive/val_split.txt'
    with open(filename, 'rb') as f:
        with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            file_size = len(mm)
            start_pos = random.randint(0, (file_size) - block_size*batch_size)

            mm.seek(start_pos)
            block = mm.read(block_size*batch_size-1)

            decoded_block = block.decode('utf-8', errors = 'ignore').replace('\r', '')

            data = torch.tensor(encode(decoded_block), dtype = torch.long)

        return data

In [30]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = get_random_chunk(split)
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    x,y = x.to(device), y.to(device)

    return x,y

x,y = get_batch('train')
print('inputs: ')
print(x.shape)
print(x)
print('targets:')
print(y)

inputs: 
torch.Size([128, 64])
tensor([[ 2, 82, 84,  ..., 73, 87, 75],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [81, 86, 74,  ..., 71, 69, 86],
        ...,
        [84, 71, 14,  ..., 79, 75, 78],
        [ 0,  0,  0,  ..., 18, 18, 18],
        [19, 85, 86,  ...,  2, 86, 74]], device='mps:0')
targets:
tensor([[82, 84, 81,  ..., 87, 75, 78],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [86, 74, 71,  ..., 69, 86, 75],
        ...,
        [71, 14,  2,  ..., 75, 78, 91],
        [ 0,  0,  0,  ..., 18, 18, 18],
        [85, 86,  2,  ..., 86, 74, 71]], device='mps:0')


In [31]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X,Y = get_batch(split)
            logits, loss = model(X,Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [ ]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1) # (B, T, F) -> (B, T, [h1, h1, h1, h1, h2, h2, h2, h2, h3, h3, h3, h3])
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        y = self.sa(x)
        x = self.ln1(x + y)
        y = self.ffwd(x)
        x = self.ln2(x + y)
        return x

class GPTLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)
        
        
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, index, targets=None):
        B, T = index.shape
        
        
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(index) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            index_cond = index[:, -block_size:]
            # get the predictions
            logits, loss = self.forward(index_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            index = torch.cat((index, index_next), dim=1) # (B, T+1)
        return index

model = GPTLanguageModel(vocab_size)
print("Loading Model Parameters...")

with open('model-01.pkl', 'rb') as f:
    model = pickle.load(f)

print("Loaded Successfully!!")
m = model.to(device)

In [ ]:
#Create a Pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step {iter}, train loss: {losses['train']:.4f}, val loss: {losses['val']:.4f}")
    
    # Sample a batch of data
    xb, yb = get_batch('train')


    # evaluate the loss
    logits, loss = model.forward(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

with open("model-01.pkl", 'wb') as f:
    pickle.dump(model, f)

step 0, train loss: 10.4572, val loss: 10.4573


KeyboardInterrupt: 

In [ ]:
context = torch.zeros((1,1), dtype=torch.long, device=device)
genererated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(genererated_chars) 



"In where bloes and, was
served trick and desired. A wheels or beauties
down all that I could find, love in his long time, and that if they had
seven fine squeetly as it was a circus as as twe can. But even get
trembled us to leave our innot."

But the little man still Dorothy:

"PRINCESTEREd


more Ozma decided the Wizard with easily and brought them. They can are quite pretty one her every ildeect seemed
to my vines. Because we zes were to go to to take them because the air was afrair or from
