In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-39,  96, -57,   8,  44, -41])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3,10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
device = 'mps' if torch.mps.is_available() else 'cpu'
print(device)

mps


In [13]:
import numpy as np
import time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0001428127


In [14]:
%%time

torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0826179981
0.5252950191
CPU times: user 874 ms, sys: 549 ms, total: 1.42 s
Wall time: 1.8 s


<timed exec>:18: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)


In [15]:
# torch.stack, torch.mulinomial, torch.trill, torch.triu, input.T/input.transpose, nn.linear, torch.cat, F.softmax

# Define Probability Tensors
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0; 90% or 0.9 => 1 each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution

samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
# torch.cat is short for torch.concatenate()

tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([-2.6008e-03,  6.5592e+00,  9.2557e+00], grad_fn=<SqueezeBackward4>)


In [24]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim = 0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [25]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 100])
tensor([[-2.8463e-01,  1.5087e+00,  2.4466e-01,  1.1488e+00, -3.0988e-01,
          9.6603e-01,  1.6072e+00, -3.8339e-01,  1.2230e+00, -5.9786e-01,
         -3.9086e-01, -1.0566e+00, -2.4765e-01,  1.2552e-01, -4.1211e-01,
          3.1325e+00, -9.6522e-01,  1.8918e+00, -4.8321e-01,  2.1032e-01,
         -1.2787e+00, -3.4198e-01, -7.9920e-01,  1.4335e-01,  8.7077e-01,
         -1.4928e+00,  1.4991e+00, -7.7808e-02, -7.5780e-01,  7.2605e-01,
         -7.3705e-01, -9.3054e-01, -1.9369e+00, -2.8424e-02, -1.8788e+00,
          1.1576e+00, -2.8198e-03,  1.7869e-02, -4.0420e-01,  7.9883e-01,
          1.7884e-01,  6.7793e-01,  4.7647e-01, -7.6011e-01,  1.3063e+00,
          7.6816e-01, -1.3820e+00,  1.1050e+00, -2.4774e-01, -2.0382e+00,
         -1.2326e-01, -7.1512e-01, -9.6920e-01, -1.0528e+00,  9.2456e-02,
         -2.6248e-01, -1.9444e+00,  5.4181e-01,  4.3090e-01, -6.4291e-01,
         -2.0604e+00, -3.4400e-02, -1.1058e+00,  1.4025e-01,  2.1564e+00,
          6.2827e

In [26]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.3162,  0.1552, -2.7023, -0.2645,  0.2772,  1.2967],
        [-0.0428,  2.4978,  0.0862, -1.6025,  1.4782,  0.6918],
        [ 0.2181,  0.1432, -1.0313,  0.1766, -0.5978, -1.1693],
        [-0.0909,  1.1764, -1.7436, -0.0526, -0.0693,  0.0817]],
       grad_fn=<EmbeddingBackward0>)


In [27]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7,8,9], [10,11,12]])

a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [30]:
int_64 = torch.randint(1,(3,2)).float()
float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [32]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(a.shape)
print(x,y,z)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])
2 3 5


In [33]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T, C)
print(output)

print(output[:, -1, :])

tensor([[0.8316, 0.4579, 0.4720, 0.2647, 0.2297, 0.2166, 0.6904, 0.0177, 0.7343,
         0.9019],
        [0.4650, 0.1992, 0.0485, 0.1530, 0.1073, 0.1249, 0.2812, 0.9585, 0.3962,
         0.2875],
        [0.2884, 0.1205, 0.1432, 0.1819, 0.7010, 0.7946, 0.8138, 0.5337, 0.7852,
         0.1950],
        [0.2200, 0.8299, 0.0237, 0.5068, 0.8073, 0.7635, 0.6105, 0.7140, 0.8473,
         0.2199],
        [0.8060, 0.2925, 0.6797, 0.2447, 0.3558, 0.4920, 0.7405, 0.3268, 0.4707,
         0.2194],
        [0.5739, 0.3175, 0.5190, 0.7186, 0.3403, 0.4046, 0.3939, 0.8819, 0.6861,
         0.0405],
        [0.6510, 0.2144, 0.8696, 0.5450, 0.9554, 0.9305, 0.3463, 0.2235, 0.2976,
         0.0424],
        [0.1022, 0.9234, 0.6928, 0.0723, 0.2550, 0.4107, 0.4822, 0.0987, 0.9576,
         0.2658],
        [0.7205, 0.4902, 0.1440, 0.2120, 0.3986, 0.4682, 0.1627, 0.1445, 0.8631,
         0.8194],
        [0.2027, 0.5653, 0.1510, 0.8096, 0.1248, 0.1463, 0.3397, 0.5253, 0.9743,
         0.1177],
        [0

IndexError: too many indices for tensor of dimension 2

In [34]:
x = torch.tensor([-0.05], dtype = torch.float32)
y = nn.ReLU(x)
print(y)

ReLU(inplace=True)


In [35]:
x = torch.tensor([-0.05], dtype = torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [36]:
x = torch.tensor([-0.05], dtype = torch.float32)
y = F.tanh(x)
print(y)

tensor([-0.0500])
